#Service startup port
server :  
  port :  8081

#Database configuration
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/simcarddb?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
mybatis:
  type-aliases-package: com.xiaour.spring.boot.mapper
  mapper-locations: classpath:mapper/*.xml
  configLocation: classpath:mybatis-config.xml
    
# 日志输出
logging: 
    file: D:/boot.log

task:
    cron:0 0/5 * * * ?
       
    
